=== judit0310/xmlproba/src/main/resources/munkahely.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="carparckschema.xsd"/>
    <xs:element name="Munkahely">
   <xs:complexType>
       <xs:all>
           <xs:element name="Telephely" type="xs:string"/>
           <xs:element name="Neve" type="xs:string"/>
           <xs:element name="Adoszam" type="adoszam_type"/>
           <xs:element name="Banszamlaszam"/>
           <xs:element name="Tevekenysegi_Kore"/>
           <xs:element name="Tulajdonos" type="szemely_type"/>
           <xs:element name="Ceges_autoflotta" type="car_park_type"/>
            <xs:element name="Dolgozok" type="dolgozo_type"/>
       </xs:all>
   </xs:complexType>

</xs:element>
<xs:complexType name="szemely_type">
    <xs:all>
        <xs:element name="Csaladnev"/>
        <xs:element name="Keresztnev"/>
        <xs:element name="Szuletesi_datum" type="xs:date"/>
        <xs:element name="Anyja_neve"/>
    </xs:all>
</xs:complexType>

    <xs:complexType name="dolgozo_type">
        <xs:complexContent>
            <xs:extension base="szemely_type">
                <xs:all>
                    <xs:element name="Munkaido"/>
                    <xs:element name="Beosztas"/>
                    <xs:element name="Szabadnapok"/>
                    <xs:element name="Ceges_telefonszam"/>
                    <xs:element name="Gyerekek_szama"/>
                    <xs:element name="Cim"/>
                    <xs:element name="Szep_kartya_szama"/>
                </xs:all>

            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="adoszam_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9]\d{7}-\d-\d\d"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== judit0310/xmlproba/src/main/resources/Munkahely.xml
<?xml version='1.0' ?>
<Munkahely xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="munkahely.xsd">
<Tulajdonos>
    <Csaladnev></Csaladnev>
    <Keresztnev></Keresztnev>
    <Szuletesi_datum>2018-05-02</Szuletesi_datum>
    <Anyja_neve></Anyja_neve>
</Tulajdonos>
    <Dolgozok>
        <Csaladnev></Csaladnev>
        <Keresztnev></Keresztnev>
        <Szuletesi_datum></Szuletesi_datum>
        <Anyja_neve></Anyja_neve>
        <Munkaido></Munkaido>
        <Beosztas></Beosztas>
        <Szabadnapok></Szabadnapok>
        <Ceges_telefonszam></Ceges_telefonszam>
        <Gyerekek_szama></Gyerekek_szama>
        <Cim></Cim>
        <Szep_kartya_szama></Szep_kartya_szama>
    </Dolgozok>
</Munkahely>
